### PR TITLE
Check effect exists before delete

### PR DESCRIPTION
**Pull request by Pietro210**
Fixes [#284](https://github.com/andrewrk/mineflayer/issues/284)

I was unable to reproduce the issue on a Vanilla server but it happened on a modded server right after the player spawned near a Beacon and the server removed the Speed effect.

### CODE REVIEW

**Comment by rom1504** [comment]
The only way not checking would be a problem is if the remove entity effect comes before the entity effect packet.
That can come from out-of-order deserialization and that's a bug we just fixed in a (not released yet) node-minecraft-protocol change.

Let's see if that's the problem before adding that check (that is a bit a hack)

**Comment by Pietro210** [comment]
That's exactly what happens in my case, the remove entity effect packet comes before the entity effect packet.

I tried again using the master branch of node-minecraft-protocol instead of the 0.13.4 release but the issue persists.

**Comment by roblabla** [comment]
TBH, this should be merged anyway as we shouldn't crash if the server tries to remove an effect we didn't have. It's similar to scoreboard handling : notchian client used to crash if the server tried to remove a non-existing scoreboard entry. Instead of crashing, it should either ignore it, or gracefully error out (emit an error event), not crash in an uncatchable way :)

**Comment by rom1504** [comment]
Ok, if that still happen with node-minecraft-protocol fix, it's possible the out-of-order problem actually from from spigot.

So ok I agree this should be checked in mineflayer. The problem with how it is fixed in this PR is this is going to emit the event entityEffectEnd with an undefined effect.
Should we still emit the event but with a { id:packet.effectId } as effect (and no amplifier and duration) or should we not emit that event at all ?

**Comment by Pietro210** [comment]
I didn't want to ignore the packet completely because I thought that some server mods with custom effects might send it, either accidentally or on purpose, and the user should know about it.

Emitting the event with an undefined effect meant something like "the server removed an entity effect but we don't know that effect" but I see that it might be a bad idea.

I pushed another commit based on @rom1504 's suggestion, now if the server removes an unknown effect the bot emits the event with a special effect object with both amplifier and duration set to -1

It might not be the best solution but it avoids crashes and doesn't break existing code that tries to access the effect's properties.

**Comment by rom1504** [comment]
Yeah that's a good enough solution.
Thanks for the PR !

**Pull request merged**
