### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### andrewrk/mineflayer now has a Chat Room on Gitter

@rom1504 has just created a chat room. You can visit it here: [https://gitter.im/andrewrk/mineflayer](https://gitter.im/andrewrk/mineflayer?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/andrewrk/mineflayer?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by rom1504** [comment]
Experimenting, idk if that room is useful, if both rooms should be referenced in the readme,...

**Comment by Gjum** [comment]
IMO only the mineflayer room should be in the readme. If a mineflayer user has an issue with nmp, they can always be redirected there.

**Comment by roblabla** [comment]
agreed, only one should be referenced in the readme.

**Comment by rom1504** [comment]
done in 221187a3708ca5d8a0ffe49c96b4877544ccef80

**Pull request closed without merging**
