### PR TITLE
Update block enum for 1.8

### PR DESCRIPTION
**Pull request by Kupferhirn**

### CODE REVIEW

**Comment by Kupferhirn** [comment]
not ready to merge

**Comment by rom1504** [comment]
Ok I just tested digging without and with the new enum for prismarine.
It doesn't work without, and it works with the new enum.

What's the problem ?

**Comment by Kupferhirn** [comment]
tested and ready to merge

**Comment by rom1504** [comment]
Ok, merging.
(I think some automatic thing https://github.com/andrewrk/mineflayer/issues/229 would be more reliable but until it's done doing it manually works)

**Pull request merged**
