### PR TITLE
Fix chest slot size conditions.

### PR DESCRIPTION
**Pull request by jimmyken793**
According to http://wiki.vg/Protocol#Open_Window , the number of slots in the packet should exclude the player inventory.

### CODE REVIEW

**Comment by roblabla** [comment]
I wonder if this PR is still relevant. @rom1504 do chests work currently ?

**Comment by rom1504** [comment]
I don't know, I haven't tested chest.js yet ;)
So I guess we'll know if that PR is still relevant once we know if it works or not yeah.

**Comment by rom1504** [comment]
Ok, chest seems to be working (without this PR).
So I'm not sure how to test this. Maybe it would break if the chest is full and the bot try to add one more item ?

**Comment by thejoshwolfe** [comment]
> Ok, chest seems to be working (without this PR).

examples/chest.js still doesn't work for me. I'm trying to debug it, and I'm stuck trying to get a 0x2d Open Window response from the server. Were you able to get some other code working with chests that I can look at?

**Comment by rom1504** [comment]
@thejoshwolfe I just tried examples/chest.js saying "chest" and all, and it just worked. Are you trying it on a vanilla server ?

**Comment by thejoshwolfe** [comment]
> Are you trying it on a vanilla server ?

yes. when i say "chest", the bot looks at the chest and swings his arm, but i don't see the chest opening animation, and the bot waits forever expecting the window open message.

 * mineflayer from source: 0d109a55b68cb92cf6a009213bdd982ede7f2061
 * node-minecraft-protocol from source: a7dd89953d855ceaaf5cd017103e9a15aeb86661 (and I ran `npm install` which ran gulp after I updated)
 * minecraft client: 1.8.3
 * minecraft server: 1.8.3

**Comment by thejoshwolfe** [comment]
> mineflayer from source: 0d109a5

just updated to f4e8051a0698fcc6ada803cca53185665bd06852, and get the same thing

**Comment by rom1504** [comment]
That's weird, I just tried one more time, and it works. Are you using a regular chest ? How far do you put the block from the chest ?

**Comment by rom1504** [comment]
I'm trying that with the "Open to lan" mode of the vanilla client, is it any different to the vanilla server ?

**Comment by thejoshwolfe** [comment]
> How far do you put the block from the chest ?

What block? Am I using this bot wrong? I just placed a chest next to him (2 blocks away) and said "chest". I thought he was supposed to list the contents of the chest.

**Comment by thejoshwolfe** [comment]
> I'm trying that with the "Open to lan" mode of the vanilla client, is it any different to the vanilla server ?

Oh my goodness. that's it. It works for me in "Open to LAN" mode as well. So the dedicated server is different then.

**Comment by rom1504** [comment]
Really oO ...
Yeah I meant "How far do you put the bot from the chest ?"

So I guess I'll have to try with an actual minecraft server...

**Comment by rom1504** [comment]
In Open to LAN did you also try in creative mode ? Does it have anything to do with creative mode or is there really a difference between the minecraft server and the open to lan mode ?

**Comment by rom1504** [comment]
So, since chest still works on minecraft_server without this PR, what to do of it ?

**Comment by rom1504** [comment]
Fixed by a02db44db3e7b8c092a0bfdbace35515bd7f6039 and PrismarineJS/minecraft-data@be51b8f4ad646a121d8b4c4a3c02f8280f62f3b2 , thanks @jimmyken793 !

**Pull request closed without merging**
